### ISSUE TITLE
No support for aliased fields

### ISSUE THREAD

**Issue by gienec** [Mikhus/graphql-fields-list#6] opened 2019-05-22 13:49 UTC
No support for aliased fields e. g. `a:myField`. In this case `a` is alias for `myField`

**Comment by Mikhus** [comment] 2019-05-27 14:26
Thank you for contribution, It definitely looks like critical missing feature... Will try to take a look on a free time or will greatly appreciate PR for this.

**Comment by Akxe** [comment] 2020-01-10 09:47
Shouldn't this be closed as implemented?

**Comment by kennetpostigo** [comment] 2020-08-11 01:07
@Akxe this hasn't been implemented.

@Mikhus any chance this will land soon? Really need it

**Comment by Akxe** [comment] 2020-08-11 15:57
There is no alias, but renaming is a feature since release.

**Comment by kennetpostigo** [comment] 2020-08-12 23:56
@Akxe i'm sorry maybe i'm misunderstanding, I have a structure like so:
```gql
query {
  team {
    id
    name
    stats {
      id
      points
    }
    players {
      id
      name
      stats {
        id
        points
        assists
      }
    }
  }
}
```

However what I see `graphql-fields-list` begin to do is:
```js
{
  ...
  stats: {
    id: false,
    points: false,
    assists: false // <-- This shouldn't be here since it's under players stats
  }
}
```

Where top level and nested fields with same field name begin to clash and get grouped together

**Comment by Akxe** [comment] 2020-08-13 07:48
This ain't alias this is to be done via computed field, but I would rather recommend you to accept that your schema might not be 100% how you would like it...

**Comment by kennetpostigo** [comment] 2020-08-16 00:46
@Akxe i'm aware thats not an alias, i'm telling you that I use an alias for this case `gameStats: stats`, but gameStats never registers.

**Comment by gienec** [comment] 2020-08-16 18:38
Well, I've solved this with in this [PR](https://github.com/robrichard/graphql-fields/pull/31) (other utility) but it won't be merged. So I would recommend to copy `graphql-fields` to you project.

**Comment by kennetpostigo** [comment] 2020-08-16 19:11
oh sweet @gienec ! I'll bring your PR in locally! Thanks a bunch!

**Comment by Mikhus** [comment] 2020-11-29 10:03
> @Akxe i'm sorry maybe i'm misunderstanding, I have a structure like so:
> 
> ```graphql
> query {
>   team {
>     id
>     name
>     stats {
>       id
>       points
>     }
>     players {
>       id
>       name
>       stats {
>         id
>         points
>         assists
>       }
>     }
>   }
> }
> ```
> 
> However what I see `graphql-fields-list` begin to do is:
> 
> ```js
> {
>   ...
>   stats: {
>     id: false,
>     points: false,
>     assists: false // <-- This shouldn't be here since it's under players stats
>   }
> }
> ```
> 
> Where top level and nested fields with same field name begin to clash and get grouped together

I've added specific tests for this case and can not reproduce such kind of behavior. For team level it resolves as:

```js
stats {
  id: false,
  points: false
}
```

where for player level it resolves as:

```js
stats {
  id: false,
  points: false,
  assists: false
}
```

which is looks like expected value and behavior (v2.2.1)

**Comment by Mikhus** [comment] 2020-11-29 10:11
> @Akxe i'm aware thats not an alias, i'm telling you that I use an alias for this case `gameStats: stats`, but gameStats never registers.

Why should it ever to be registered? At my understanding alias is something to be resolved on a client side (query result), whenever stats is something which is expected to be resolved on a back-end side. It works exactly in this way - whatever alias is set for some field by a client on a server it is resolved to a schema field definition which is then used to get the data from some storage.

Can you, please, provide an example, where you might need behave controversially, what is the essence to get an alias  instead of exact field name?

**Closed as completed** 2020-11-30 00:36 UTC
Labels: invalid, question
